name: Build WPF Application

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
env:
  PROJECT_PATH: Dev_ToolBox\Dev_ToolBox.csproj
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Build WPF Application
      run: dotnet build -c Release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
