name: Build WPF Application and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
      
env:
  PROJECT_PATH: Dev_ToolBox/Dev_ToolBox.csproj

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - name: Zip
        run: Compress-Archive -Path ./Dev_ToolBox/bin/Release -DestinationPath ./Draft.zip
        shell: powershell

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: Dev_ToolBox
            path: ./Draft.zip

      - name: Version as date
        id: get_version
        run: echo "::set-output name=version::$(Get-Date -Format 'yyyy.MM.dd.HHmmss')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Add asset
        uses: AButler/upload-release-assets@v3.0
        with:
         files: ./Draft.zip
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         release-tag: ${{ steps.get_version.outputs.version }}