name: Build and Create Installer

on:
  push:
    branches:
      - main
    tags:
      - "v*"
      
env:
  PROJECT_PATH: Dev_ToolBox/Dev_ToolBox.csproj

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
        id-token: write
        contents: read
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup .NET  
      - name: Setup .NET Core SDK 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      # Restore NuGet packages
      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      # Build the application
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      # Install Inno Setup
      - name: Install Inno Setup
        run: |
          Invoke-WebRequest -Uri https://jrsoftware.org/download.php/is.exe -OutFile is.exe
          Start-Process -Wait -FilePath .\is.exe -ArgumentList '/VERYSILENT', '/DIR="C:\InnoSetup"'

      # Create Installer
      - name: Create Installer
        run: |
          Start-Process -FilePath "C:\InnoSetup\ISCC.exe" -ArgumentList "Dev_toolBox/setup.iss" -Wait
        env:
          PATH: ${{ runner.temp }};C:\InnoSetup

      # Create a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Output\Dev_ToolBox_Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOOL_TOKEN }}

      # - name: Zip
      #   run: Compress-Archive -Path ./Dev_ToolBox/bin/Release -DestinationPath ./Dev_ToolBox.zip
      #   shell: powershell

      # - name: Version as date
      #   id: get_version
      #   run: echo "::set-output name=version::$(Get-Date -Format 'yyyy.MM.dd')"

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.DEV_TOOL_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.get_version.outputs.version }}
      #     release_name: Release ${{ steps.get_version.outputs.version }}
      #     draft: false
      #     prerelease: false

      # - name: Add asset
      #   uses: AButler/upload-release-assets@v3.0
      #   with:
      #    files: ./Dev_ToolBox.zip
      #    repo-token: ${{ secrets.DEV_TOOL_TOKEN }}
      #    release-tag: ${{ steps.get_version.outputs.version }}
