name: Build and Create setup

on:
  push:
    branches:
      - main
    tags:
      - "v*"
      
env:
  PROJECT_PATH: Dev_ToolBox/Dev_ToolBox.csproj

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
        id-token: write
        contents: read
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup .NET  
      - name: Setup .NET Core SDK 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      # Restore NuGet packages
      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      # Build the application
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - name: Log Current Working Directory
        run: |
          echo "Current working directory: $(pwd)"
      
      - name: Verify build output
        run: |
          if (!(Test-Path D:\a\Dev_ToolBox\Dev_ToolBox\Dev_ToolBox\bin\Release\net8.0-windows10.0.19041.0\win-x64\publish)) {
            echo "Build output directory does not exist."
            exit 1
          } else {
            echo "Build output directory exists."
            Get-ChildItem -Path D:\a\Dev_ToolBox\Dev_ToolBox\Dev_ToolBox\bin\Release\net8.0-windows10.0.19041.0\win-x64\publish -Recurse
          }

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes
        shell: cmd

      - name: Create Inno Setup Script
        run: |
          echo ; Script generated by GitHub Actions > setup.iss
          echo [Setup] >> setup.iss
          echo AppName=Dev ToolBox >> setup.iss
          echo AppVersion=1.0.0 >> setup.iss
          echo DefaultDirName={pf}\Dev ToolBox >> setup.iss
          echo DefaultGroupName=Dev ToolBox >> setup.iss
          echo OutputDir=output >> setup.iss
          echo OutputBaseFilename=Dev ToolBoxsetup >> setup.iss
          echo Compression=lzma2 >> setup.iss
          echo SolidCompression=yes >> setup.iss
          echo [Files] >> setup.iss
          echo SourceDir=.\dist\ >> setup.iss
          echo Source: *.*; DestDir: {app}; Flags: ignoreversion >> setup.iss
          echo [Icons] >> setup.iss
          echo Name: {group}\Dev ToolBox; Filename: {app}\Dev ToolBox.exe >> setup.iss
        shell: cmd

      - name: Version as date
        id: get_version
        run: echo "{name}=version::$(Get-Date -Format 'yyyy.MM.dd')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOOL_TOKEN }}
        with:
          tag_name: tag
          release_name: Release
          draft: false
          prerelease: false
  
      - name: Upload setup
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOOL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\Dev_ToolBox\Dev_ToolBox\Dev_ToolBox\bin\Release\setup\Dev_ToolBox_Setup.exe
          asset_name: "Dev_ToolBox_Setup.exe"
          asset_content_type: application/vnd.microsoft.portable-executable

      # - name: Zip
      #   run: Compress-Archive -Path ./Dev_ToolBox/bin/Release -DestinationPath ./Dev_ToolBox.zip
      #   shell: powershell

      # - name: Version as date
      #   id: get_version
      #   run: echo "::set-output name=version::$(Get-Date -Format 'yyyy.MM.dd')"

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.DEV_TOOL_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.get_version.outputs.version }}
      #     release_name: Release ${{ steps.get_version.outputs.version }}
      #     draft: false
      #     prerelease: false

      # - name: Add asset
      #   uses: AButler/upload-release-assets@v3.0
      #   with:
      #    files: ./Dev_ToolBox.zip
      #    repo-token: ${{ secrets.DEV_TOOL_TOKEN }}
      #    release-tag: ${{ steps.get_version.outputs.version }}
