name: Build and Create setup

on:
  push:
    branches:
      - main
      
env:
  PROJECT_PATH: Dev_ToolBox/Dev_ToolBox.csproj
  BUILD_OUTPUT_PATH: Dev_ToolBox/Dev_ToolBox/bin/Release/net8.0-windows10.0.19041.0/win-x64/publish/

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
        id-token: write
        contents: read
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup .NET  
      - name: Setup .NET Core SDK 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      # Restore NuGet packages
      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      # Build the application
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - name: Verify build output
        run: |
          if (!(Test-Path D:\a\Dev_ToolBox\Dev_ToolBox\Dev_ToolBox\bin\Release\net8.0-windows10.0.19041.0\win-x64\publish)) {
            echo "Build output directory does not exist."
            exit 1
          } else {
            echo "Build output directory exists."
            Get-ChildItem -Path D:\a\Dev_ToolBox\Dev_ToolBox\Dev_ToolBox\bin\Release\net8.0-windows10.0.19041.0\win-x64\publish -Recurse
          }

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes
        shell: cmd

      - name: Create Inno Setup Script
        run: |
          echo ; Script generated by GitHub Actions > setup.iss
          echo [Setup] >> setup.iss
          echo AppName=DevToolBox >> setup.iss
          echo AppVersion=1.0.0 >> setup.iss
          echo DefaultDirName={pf}\DevToolBox >> setup.iss
          echo DefaultGroupName=DevToolBox >> setup.iss
          echo OutputDir=output >> setup.iss
          echo OutputBaseFilename=DevToolBoxsetup >> setup.iss
          echo Compression=lzma2 >> setup.iss
          echo SolidCompression=yes >> setup.iss
          echo [Files] >> setup.iss
          echo Source: "Dev_ToolBox\bin\Release\net8.0-windows10.0.19041.0\win-x64\*"; DestDir: {app}; Flags: ignoreversion >> setup.iss
          echo [Icons] >> setup.iss
          echo Name: {group}\Dev ToolBox; Filename: {app}\Dev_ToolBox.exe >> setup.iss
        shell: cmd

      - name: Compile Inno Setup Script
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss
        shell: cmd
      
      # Zip the setup folder
      - name: Zip the setup folder
        run: |
          Compress-Archive -Path output -DestinationPath DevToolBoxsetup.zip

      # Verify zip output
      - name: Verify zip output
        run: |
          if (!(Test-Path DevToolBoxsetup.zip)) {
            echo "Zip file does not exist."
            exit 1
          } else {
            echo "Zip file exists."
            Get-ChildItem -Path DevToolBoxsetup.zip
          }

      # Upload Zipped Installer Artifact
      - name: Upload Zipped Installer Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DevToolBoxsetup
          path: DevToolBoxsetup.zip
          if-no-files-found: warn
          
      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOOL_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: DevToolBox Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
  
      # Upload Zipped Setup File to Release
      - name: Upload Setup Zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOOL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: DevToolBoxsetup.zip
          asset_name: "DevToolBoxsetup.zip"
          asset_content_type: application/zip