name: Build WPF Application and Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
env:
  PROJECT_PATH: Dev_ToolBox\Dev_ToolBox.csproj
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Build WPF Application
      run: dotnet build -c Release

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          your-program-name-here-linux
          your-program-name-here-macos
          your-program-name-here-win.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
